### ISSUE TITLE
Entities unavailable after power cycle

### ISSUE THREAD

**Issue by jack00075** [gazoodle/gecko-home-assistant#169]
## System Information

version | core-2025.2.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 3.10.108
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 1685
Downloaded Repositories | 22

</details>

<details><summary>Solcast Solar</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 6
views | 16
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | tun0 (enabled, default, auto), lo (disabled), ovs_eth0 (disabled), ovs_eth1 (disabled), docker0 (disabled), docker3458ab4 (disabled), docker9b247e5 (disabled)
-- | --
ipv4_addresses | tun0 (10.8.5.217/24), lo (127.0.0.1/8), ovs_eth0 (192.168.1.10/24), ovs_eth1 (192.168.2.1/16), docker0 (172.17.0.1/16), docker3458ab4 (), docker9b247e5 ()
ipv6_addresses | tun0 (fc00:db8:0:1::10d7/64), lo (::1/128), ovs_eth0 (), ovs_eth1 (), docker0 (fe80::42:7bff:febe:7a4e/64), docker3458ab4 (fe80::541d:ccff:fef3:dcc0/64), docker9b247e5 (fe80::ecb4:cfff:fe13:9ccd/64)
announce_addresses | 10.8.5.217, fc00:db8:0:1::10d7

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 23, 2025 at 8:37 PM
-- | --
current_recorder_run | April 2, 2025 at 8:35 PM
estimated_db_size | 395.70 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/gazoodle/gecko-home-assistant/issues)

### Describe the issue

Entities unavailable after power cycle. I need to reload the integration to be able to see all entities admin. All is working in update 1.18.

### Reproduction steps

1.when spa I poweredon and connected I need to reload the integration.
2.power off spa and power on again. 
3.the integration will not automatically connect.
4. I neto reload integration to be able to see entities. 
...

### Debug logs

```text
2025-03-29 03:50:41.314 ERROR (MainThread) [geckolib.async_spa] Cannot get reminders, protocol retry time exceeded

2025-03-29 03:50:42.350 ERROR (MainThread) [homeassistant.components.button] Error while setting up gecko platform for button: 'NoneType' object has no attribute 'name'

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform

    await asyncio.shield(awaitable)

  File "/config/custom_components/gecko/button.py", line 28, in async_setup_entry

    buttons.append(GeckoSnapshotButton(entry, spaman))

                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/config/custom_components/gecko/button.py", line 89, in __init__

    spaman.facade.name,

    ^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'name'

2025-03-29 03:50:42.379 ERROR (MainThread) [homeassistant.components.select] Error while setting up gecko platform for select:

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform

    await asyncio.shield(awaitable)

  File "/config/custom_components/gecko/select.py", line 26, in async_setup_entry

    assert spaman.facade is not None  # noqa: S101

           ^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError

2025-03-29 03:50:42.424 WARNING (MainThread) [homeassistant.components.template.trigger] Error evaluating 'template' trigger for 'Swim Spa Heating - Monitor Temperature': ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{

  states('sensor.alps_swimspa_current_temperature') | float >=

  states('sensor.alps_swimspa_target_temperature') | float or

  states('sensor.alps_swimspa_current_temperature') | float <

  (states('sensor.alps_swimspa_target_temperature') | float -

  states('input_number.temperature_hysteresis') | float)

}}' but no default was specified

 

2025-03-31 05:57:30.190 ERROR (MainThread) [custom_components.tuya_local.device] Failed to update device dps for Energy monitoring smartplug_DOBUDOWKA

2025-03-31 05:57:41.662 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:57:54.768 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:58:07.876 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:58:20.988 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:58:34.098 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:58:47.208 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:59:00.323 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:59:13.436 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:59:26.554 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:59:39.666 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 05:59:52.780 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:00:05.894 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:00:19.019 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:00:32.133 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:00:45.251 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:00:58.363 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:01:11.500 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:01:24.623 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:01:37.738 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:01:50.855 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:02:03.978 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:02:17.098 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 06:02:30.223 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

.

.

.

2025-03-31 17:44:58.766 WARNING (SyncWorker_16) [homeassistant.loader] We found a custom integration gecko which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2025-03-31 17:45:20.739 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140285031850064] Unexpected exception

Traceback (most recent call last):

  File "/config/custom_components/hacs/update.py", line 88, in async_install

    await self.repository.async_download_repository(ref=version or self.latest_version)

  File "/config/custom_components/hacs/repositories/base.py", line 1414, in async_download_repository

    await self._ensure_download_capabilities(ref)

  File "/config/custom_components/hacs/repositories/base.py", line 1404, in _ensure_download_capabilities

    raise HacsException(

    ...<2 lines>...

    )

custom_components.hacs.exceptions.HacsException: This version requires Home Assistant 2025.2.5 or newer.

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service

    response = await hass.services.async_call(

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    ...<7 lines>...

    )

    ^

  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call

    response_data = await coro

                    ^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service

    return await target(service_call)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call

    single_response = await _handle_entity_call(

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

        hass, entity, func, data, call.context

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call

    result = await task

             ^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install

    await entity.async_install_with_progress(version, backup)

  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 489, in async_install_with_progress

    await self.async_install(version, backup)

  File "/config/custom_components/hacs/update.py", line 90, in async_install

    raise HomeAssistantError(exception) from exception

homeassistant.exceptions.HomeAssistantError: This version requires Home Assistant 2025.2.5 or newer.

2025-03-31 18:42:14.516 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 18:42:26.637 ERROR (MainThread) [custom_components.tuya_local.device] Failed to update device dps for Energy monitoring smartplug_DOBUDOWKA

2025-03-31 18:42:27.623 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 18:42:40.736 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 18:42:53.851 ERROR (MainThread) [geckolib.async_spa] Cannot get file, protocol retry time exceeded

2025-03-31 18:43:00.400 ERROR (MainThread) [geckolib.driver.udp_protocol_handler] Consume loop for GeckoWatercareErrorHandler(send_bytes=None, age=0.0017324667423963547, should_remove_handler=False, timeout=0s)(parms=None, content=None) caught exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.13/site-packages/geckolib/driver/udp_protocol_handler.py", line 202, in consume

    await self.async_handled(sender)

  File "/usr/local/lib/python3.13/site-packages/geckolib/driver/udp_protocol_handler.py", line 132, in async_handled

    await self._async_on_handled(self, sender)

  File "/usr/local/lib/python3.13/site-packages/geckolib/async_spa.py", line 718, in _async_on_wcerr

    await self._event_handler(GeckoSpaEvent.RUNNING_SPA_WATER_CARE_ERROR)

  File "/usr/local/lib/python3.13/site-packages/geckolib/async_spa_manager.py", line 587, in _handle_event

    assert self.facade is not None  # noqa: S101

           ^^^^^^^^^^^^^^^^^^^^^^^

AssertionError

2025-03-31 19:04:45.840 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:47.860 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:49.879 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:51.898 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:53.917 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:55.936 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:57.954 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:04:59.974 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTED

2025-03-31 19:05:00.067 DEBUG (MainThread) [custom_components.gecko.spa_manager] Unload platforms ['binary_sensor', 'button', 'fan', 'sensor', 'switch', 'climate', 'light', 'select', 'water_heater', 'date', 'number']

2025-03-31 19:05:00.080 DEBUG (MainThread) [custom_components.gecko] Close SpaMan

2025-03-31 19:05:00.082 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CLIENT_FACADE_TEARDOWN, state GeckoSpaState.IDLE

2025-03-31 19:05:00.082 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_SPA_DISCONNECTED, state GeckoSpaState.IDLE

2025-03-31 19:05:00.091 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.SPA_MAN_EXIT, state GeckoSpaState.IDLE

2025-03-31 19:05:00.093 DEBUG (MainThread) [custom_components.gecko] Setup entry for UUID be8cb584-595d-4c8f-850f-25eb40e9ad73, ID SPAe8:eb:1b:3b:c3:05, address 192.168.1.149 (Alps swimspa)

2025-03-31 19:05:00.094 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CLIENT_HAS_STATUS_SENSOR, state GeckoSpaState.IDLE

2025-03-31 19:05:00.094 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.SPA_MAN_ENTER, state GeckoSpaState.IDLE

2025-03-31 19:05:00.098 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.LOCATING_STARTED, state GeckoSpaState.LOCATING_SPAS

2025-03-31 19:05:00.099 DEBUG (MainThread) [custom_components.gecko.spa_manager] Load platforms ['sensor', 'button']

2025-03-31 19:05:00.100 INFO (MainThread) [custom_components.gecko.entity] Setup entity Status/SPAe8eb1b3bc305-STATUS

2025-03-31 19:05:00.114 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.LOCATING_DISCOVERED_SPA, state GeckoSpaState.LOCATING_SPAS

2025-03-31 19:05:01.111 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.LOCATING_FINISHED, state GeckoSpaState.LOCATED_SPAS

2025-03-31 19:05:01.112 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CLIENT_HAS_RECONNECT_BUTTON, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.112 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CONNECTION_STARTED, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.113 DEBUG (MainThread) [custom_components.gecko.spa_manager] Unload platforms ['sensor', 'button']

2025-03-31 19:05:01.114 DEBUG (MainThread) [custom_components.gecko.spa_manager] Load platforms ['sensor', 'button']

2025-03-31 19:05:01.115 INFO (MainThread) [custom_components.gecko.entity] Setup entity Status/SPAe8eb1b3bc305-STATUS

2025-03-31 19:05:01.117 INFO (MainThread) [custom_components.gecko.entity] Setup entity Reconnect/SPAe8eb1b3bc305-RECONNECT

2025-03-31 19:05:01.151 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.RUNNING_PING_RECEIVED, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.177 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CONNECTION_GOT_FIRMWARE_VERSION, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.198 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CLIENT_HAS_PING_SENSOR, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.198 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CONNECTION_GOT_CHANNEL, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.394 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CONNECTION_GOT_CONFIG_FILES, state GeckoSpaState.CONNECTING

2025-03-31 19:05:01.395 DEBUG (MainThread) [custom_components.gecko.spa_manager] Event: GeckoSpaEvent.CONNECTION_INITIAL_DATA_BLOCK_REQUEST, state GeckoSpaState.CONNECTING
```

**Comment by jack00075** [comment]
I need to reload integration after  the spa is switched off and on again. This was working before in version  0.1.18

**Comment by jack00075** [comment]
I have sorted this issue by automatically reconnecting if the connection is lost.(Reconnect button)
